version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: h1_postgres
    environment:
      POSTGRES_USER: h1user
      POSTGRES_PASSWORD: h1password
      POSTGRES_DB: h1jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - h1_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: h1_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - h1_network

  redis:
    image: redis:7-alpine
    container_name: h1_redis
    ports:
      - "6379:6379"
    networks:
      - h1_network

volumes:
  postgres_data:
  es_data:

networks:
  h1_network:
    driver: bridge
